### ISSUE TITLE
Manually analyze CCN for RTFChars::transformSpecialCharacter

### ISSUE THREAD

**Issue by henkejo** [DD2480-gr25/jabref#1]
RTFChars::transformSpecialCharacter@208-345@src\main\java\org\jabref\logic\layout\format\RTFChars.java

**Comment by pontuscm** [comment]
+80 if statements (8) with 5 clauses (&& / ||)
+24 if statements (6) with 2 clauses (&& / ||)
+70 if statements (5) with 7 clauses (&& / ||)
+12 if statements (1) with 6 clauses (&& / ||)
+13 if statements (13) with 1 clauses (&& / ||)
+42 if statements (7) with 3 clauses (&& / ||)
+40 if statements (5) with 4 clauses (&& / ||)
-46 return (46)
= 281 - 46 + 2 = 237

**Comment by xinyiwan** [comment]
+65 if 
+20 &&
+99 ||
+1 while
+2 for
+3 case
-48 return

In total :65 + 20 + 99 + 1 + 2 + 3 - 48 - 0 +2 = 144
I count the decision points including if, &&, ||, while, for and case, rather than branches.

**Comment by xinyiwan** [comment]
The difference between two results is mainly due to counting branches or decisions for CC. For, while, case are not considered in the first calculation. Also counting results of the exits are slightly different.
