### ISSUE TITLE
Manually analyze CCN for RisImporter

### ISSUE THREAD

**Issue by henkejo** [DD2480-gr25/jabref#2]
RisImporter::importDatabase@58-312@src\main\java\org\jabref\logic\importer\fileformat\RisImporter.java

**Comment by henkejo** [comment]
Hi! These were my results of the count for RisImporter

```
47 else if
25 if (times 2 because of implicit else) = 50
2 for
1 while
2 try-catch (not including these)
------------------
= 100 branches


1 return
------------
= 1 exit


Result: CCN = 99
```

**Comment by henkejo** [comment]
Forgot the `+2` from the lecture formula. So:

``Result: CCN = 101``

**Comment by xinyiwan** [comment]
Method 1: according to the slides, counting number of decisions

IF : 68
While:  1
For:2
&&: 8 
||:  28

Return: 5
Throw:2

= 68 + 1 + 2 + 8 + 28 - 5 - 2 + 2 = 102

-----------------------------------------
Method 2: V = P + 1
Where P = Number of predicate nodes (node that contains condition)

if  with 1 condition : 40 
if  with 2 conditions : 10
if  with 3 conditions : 6 
if  with 4 conditions : 1 
if  with 5 conditions : 2
for : 1
while : 1

CC = 40 + 10*2 + 6*3 +1*4 + 2*5  + 1 + 1 + 1 =103

**Comment by xinyiwan** [comment]
We got very similar result, but we calculated in different ways. The difference is adding branches or decision nodes in the formula. According to some articles about CC, there are two ways to do this : 1) pi  - s + 2 ; 2) N(decision nodes) + 1.  When we both used first way, the number of branches ( or decision nodes) cause the slight difference.
