### ISSUE TITLE
Manually analyze CCN for GvkParser::parseEntry

### ISSUE THREAD

**Issue by henkejo** [DD2480-gr25/jabref#3]
GvkParser::parseEntry@74-442@src\main\java\org\jabref\logic\importer\fileformat\GvkParser.java

**Comment by pontuscm** [comment]
+1 for loop
+62 if (68-6)
+16 if (4) with && (4)
+6 if (1) with && (1) and || (1)
+8 if (1) with && (2) and || (1)
+3 else
-1 return
= pi - s + 2 = 96 - 1 + 2 = **97**

**Comment by emiros98** [comment]
Based on (decisions - endpoints + 2) (decisions being while, if, &&, and ||)

68 if + 7 && + 2 || - 1 return + 2 = 77 - 1 + 2 = 78

**Comment by emiros98** [comment]
The different results are a result of using different methods for counting. We both counted the same number of if, &&, and ||, but Pontus took branches into account in a way that I didn't.
